-- HACK: This file is not part of the `neovim-configuration` directory but rather automatically generated by Nix and linked using home-manager.
local colors = require("colors")

local opts = {
    base00 = colors.base00,
    base01 = colors.base01,
    base02 = colors.base02,
    base03 = colors.base03,
    base04 = colors.base04,
    base05 = colors.base05,
    base06 = colors.base06,
    base07 = colors.base07,
    base08 = colors.base08,
    base09 = colors.base09,
    base0A = colors.base0A,
    base0B = colors.base0B,
    base0C = colors.base0C,
    base0D = colors.base0D,
    base0E = colors.base0E,
    base0F = colors.base0F,
}

local function config()
    local colorscheme = require('base16-colorscheme')
    colorscheme.setup(opts)

    local highlight_groups = colorscheme.highlight
    highlight_groups.Normal = { guibg = "NONE" }
    highlight_groups.Visual = { guibg = colors.base08, guifg = colors.base00 }
    highlight_groups.HighlightYankedText = { guibg = colors.base0B }
    highlight_groups.CmpItemAbbr = { guifg = colors.base05 }
    highlight_groups.LineNr = { guifg = colors.base0B }
    highlight_groups.Cursor = { gui = "reverse" }

    -- LSP types
    highlight_groups["@lsp.type.parameter"] = { guifg = colors.base0B, gui = "italic" }
    highlight_groups["@lsp.type.typeParameter"] = { guifg = colors.base0A, gui = "bold" }
    highlight_groups["@lsp.type.namespace"] = { guifg = colors.base0C, gui = "italic" }

    -- Diagnostics
    highlight_groups.DiagnosticError = { guifg = colors.base01, guibg = colors.base08 }
    highlight_groups.DiagnosticWarn = { guifg = colors.base01, guibg = colors.base09 }
    highlight_groups.DiagnosticInfo = { guifg = colors.base01, guibg = colors.base0B }
    highlight_groups.DiagnosticHint = { guifg = colors.base01, guibg = colors.base0C }

    -- Noice
    highlight_groups.NoiceCmdlinePopupBorder = { guifg = colors.base0C }
    highlight_groups.NoiceCmdlineIcon = { guifg = colors.base0C }
    highlight_groups.NoiceCmdlinePopupBorderSearch = { guifg = colors.base09 }
    highlight_groups.NoiceCmdlineIconSearch = { guifg = colors.base09 }

    -- todo-comments
    -- WARN: Warn
    -- TODO: Todo
    -- TEST: Test
    -- PERF: Perf
    -- NOTE: Note
    -- HACK: Hack
    -- FIX: Fix

    -- todo-comments signs
    highlight_groups.TodoSignWARN = { guifg = colors.base09, guibg = colors.base00 }
    highlight_groups.TodoSignTODO = { guifg = colors.base0E, guibg = colors.base00 }
    highlight_groups.TodoSignTEST = { guifg = colors.base0A, guibg = colors.base00 }
    highlight_groups.TodoSignPERF = { guifg = colors.base0B, guibg = colors.base00 }
    highlight_groups.TodoSignNOTE = { guifg = colors.base0C, guibg = colors.base00 }
    highlight_groups.TodoSignHACK = { guifg = colors.base08, guibg = colors.base00 }
    highlight_groups.TodoSignFIX = { guifg = colors.base08, guibg = colors.base00 }

    -- todo-comments background
    highlight_groups.TodoBgWARN = { guibg = colors.base09, guifg = colors.base00, gui = 'bold' }
    highlight_groups.TodoBgTODO = { guibg = colors.base0E, guifg = colors.base00, gui = 'bold' }
    highlight_groups.TodoBgTEST = { guibg = colors.base0A, guifg = colors.base00, gui = 'bold' }
    highlight_groups.TodoBgPERF = { guibg = colors.base0B, guifg = colors.base00, gui = 'bold' }
    highlight_groups.TodoBgNOTE = { guibg = colors.base0C, guifg = colors.base00, gui = 'bold' }
    highlight_groups.TodoBgHACK = { guibg = colors.base08, guifg = colors.base00, gui = 'bold' }
    highlight_groups.TodoBgFIX = { guibg = colors.base08, guifg = colors.base00, gui = 'bold' }

    -- todo-comments foreground
    highlight_groups.TodoFgWARN = { guifg = colors.base0A }
    highlight_groups.TodoFgTODO = { guifg = colors.base0C }
    highlight_groups.TodoFgTEST = { guifg = colors.base0D }
    highlight_groups.TodoFgPERF = { guifg = colors.base0E }
    highlight_groups.TodoFgNOTE = { guifg = colors.base07 }
    highlight_groups.TodoFgHACK = { guifg = colors.base09 }
    highlight_groups.TodoFgFIX = { guifg = colors.base0A }

    -- bookmarks
    highlight_groups.Bookmark = { guifg = colors.base01, guibg = colors.base0B }

    -- find-mode
    highlight_groups.FindModeLine = { guifg = colors.base09 }
    highlight_groups.FindModeMatch = { guifg = colors.base0C, gui = 'italic' }

    -- blink.cmp
    highlight_groups.BlinkCmpKindClass = { guifg = colors.base0C }
    highlight_groups.BlinkCmpKindColor = { guifg = colors.base0D }
    highlight_groups.BlinkCmpKindConstant = { guifg = colors.base0E }
    highlight_groups.BlinkCmpKindConstructor = { guifg = colors.base0C }
    highlight_groups.BlinkCmpKindEnum = { guifg = colors.base0A }
    highlight_groups.BlinkCmpKindEnumMember = { guifg = colors.base0A }
    highlight_groups.BlinkCmpKindEvent = { guifg = colors.base0F }
    highlight_groups.BlinkCmpKindField = { guifg = colors.base0A }
    highlight_groups.BlinkCmpKindFile = { guifg = colors.base09 }
    highlight_groups.BlinkCmpKindFolder = { guifg = colors.base08 }
    highlight_groups.BlinkCmpKindFunction = { guifg = colors.base0A }
    highlight_groups.BlinkCmpKindInterface = { guifg = colors.base0E }
    highlight_groups.BlinkCmpKindKeyword = { guifg = colors.base0F }
    highlight_groups.BlinkCmpKindMethod = { guifg = colors.base0C }
    highlight_groups.BlinkCmpKindModule = { guifg = colors.base07 }
    highlight_groups.BlinkCmpKindOperator = { guifg = colors.base0B }
    highlight_groups.BlinkCmpKindProperty = { guifg = colors.base0C }
    highlight_groups.BlinkCmpKindReference = { guifg = colors.base0F }
    highlight_groups.BlinkCmpKindRipgrepGit = { guifg = colors.base0B }
    highlight_groups.BlinkCmpKindSnippet = { guifg = colors.base0E }
    highlight_groups.BlinkCmpKindText = { guifg = colors.base0D }
    highlight_groups.BlinkCmpKindTypeParameter = { guifg = colors.base0D }
    highlight_groups.BlinkCmpKindUnit = { guifg = colors.base0B }
    highlight_groups.BlinkCmpKindValue = { guifg = colors.base0B }
    highlight_groups.BlinkCmpKindVariable = { guifg = colors.base0D }
    highlight_groups.BlinkCmpKindStruct = { guifg = colors.base09 }
end

return {
    'RRethy/nvim-base16',
    priority = 1000,
    config = config,
}
